<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <VersionPrefix>26.0.1</VersionPrefix>
    <Authors>Dietmar Oettl;Markus Kuntner</Authors>
    <Copyright>2025 Oettl, Kuntner [GPLv3]</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <AssemblyTitle>GRAL</AssemblyTitle>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <Optimize>true</Optimize>
    <TieredCompilation>true</TieredCompilation>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <DOTNET_TC_QuickJitForLoops>false</DOTNET_TC_QuickJitForLoops>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TieredPGO>true</TieredPGO>
    <DOTNET_EnableDiagnostics>false</DOTNET_EnableDiagnostics>
    <DOTNET_ENABLE_PROFILING>false</DOTNET_ENABLE_PROFILING>
    <RetainVMGarbageCollection>false</RetainVMGarbageCollection>
    <GarbageCollectionAdaptationMode>0</GarbageCollectionAdaptationMode>
    <DebugType>embedded</DebugType>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <!-- 
    <PublishAot>true</PublishAot>
    -->
  </PropertyGroup>

</Project>
 